#include "error.h"

const char* err_to_str(const error_code_t err) {
    switch (err) {
    case SUCCESS: return "SUCCESS";
    case GENERIC_ERROR: return "GENERIC_ERROR";
    case NULLPTR_PARAMETER_ERROR: return "NULLPTR_PARAMETER_ERROR";
    case OPEN_FILE_FAILED: return "OPEN_FILE_FAILED";
    case READ_FAILED: return "READ_FAILED";
    case MALFORMED_STATUS_LINE: return "MALFORMED_STATUS_LINE";
    case UID_NOT_FOUND: return "UID_NOT_FOUND";
    case USER_NOT_FOUND: return "USER_NOT_FOUND";
    case MEMORY_ALLOCATION_FAILED: return "MEMORY_ALLOCATION_FAILED";
    case PARSING_FAILED: return "PARSING_FAILED";
    case THREAD_FAILED: return "THREAD_FAILED";
    case SEND_SIGNAL_PIDFD_OPEN_FAILED: return "SEND_SIGNAL_PIDFD_OPEN_FAILED";
    case SEND_SIGNAL_SEND_FAILED: return "SEND_SIGNAL_SEND_FAILED";
    case SEND_SIGNAL_WAIT_FAILED: return "SEND_SIGNAL_WAIT_FAILED";
    case PID_DOES_NOT_EXIST: return "PID_DOES_NOT_EXIST";
    case FORK_FAILED: return "FORK_FAILED";
    case TIMEOUT: return "TIMEOUT";
    case READ_CFG_SERVER_NAME_FAILED: return "READ_CFG_SERVER_NAME_FAILED";
    case READ_CFG_SERVER_ADDR_FAILED: return "READ_CFG_SERVER_ADDR_FAILED";
    case READ_CFG_PORT_FAILED: return "READ_CFG_PORT_FAILED";
    case READ_CFG_USERNAME_FAILED: return "READ_CFG_USERNAME_FAILED";
    case READ_CFG_PASSWORD_FAILED: return "READ_CFG_PASSWORD_FAILED";
    case READ_CFG_CONNEXION_FAILED: return "READ_CFG_CONNEXION_FAILED";
    case INVALID_ARGUMENT: return "INVALID_ARGUMENT";
    case FILE_DOES_NOT_EXIST: return "FILE_DOES_NOT_EXIST";
    case UNREGULAR_FILE_ERROR: return "UNREGULAR_FILE_ERROR";
    case BAD_PERMISSIONS_ERROR: return "BAD_PERMISSIONS_ERROR";
	default: return "UNKNOWN_ERROR";
    }
}

