#ifndef ERROR_H
#define ERROR_H

typedef enum error_code_t : int {
  SUCCESS,
  GENERIC_ERROR,
  NULLPTR_PARAMETER_ERROR,
  OPEN_FILE_FAILED,
  READ_FAILED,
  MALFORMED_STATUS_LINE,
  UID_NOT_FOUND,
  USER_NOT_FOUND,
  MEMORY_ALLOCATION_FAILED,
  PARSING_FAILED,
  THREAD_FAILED,
  SEND_SIGNAL_PIDFD_OPEN_FAILED,
  SEND_SIGNAL_SEND_FAILED,
  SEND_SIGNAL_WAIT_FAILED,
  PID_DOES_NOT_EXIST,
  FORK_FAILED,
  TIMEOUT,
  READ_CFG_SERVER_NAME_FAILED,
  READ_CFG_SERVER_ADDR_FAILED,
  READ_CFG_PORT_FAILED,
  READ_CFG_USERNAME_FAILED,
  READ_CFG_PASSWORD_FAILED,
  READ_CFG_CONNEXION_FAILED,
  INVALID_NUMERIC_DATA,
  INVALID_CONNEXION_TYPE,
  FILE_DOES_NOT_EXIST,
  UNREGULAR_FILE_ERROR,
  BAD_PERMISSIONS_ERROR,
  PATH_TOO_LONG_ERROR,
  INVALID_PATH,
} error_code_t;

#endif // ERROR_H
