#ifndef ERROR_H
#define ERROR_H

typedef enum error_code_t : int {
  SUCCESS,
  GENERIC_ERROR,
  NULLPTR_PARAMETER_ERROR,
  OPEN_FILE_FAILED,
  READ_FAILED,
  MALFORMED_STATUS_LINE,
  UID_NOT_FOUND,
  USER_NOT_FOUND,
  MEMORY_ALLOCATION_FAILED,
  PARSING_FAILED,
  THREAD_FAILED,
  SEND_SIGNAL_PIDFD_OPEN_FAILED,
  SEND_SIGNAL_SEND_FAILED,
  SEND_SIGNAL_WAIT_FAILED,
  PID_DOES_NOT_EXIST,
  FORK_FAILED,
  TIMEOUT,
} error_code_t;

#endif // ERROR_H
