#include "error.h"

const char *err_to_str(const error_code_t err) {
    switch (err) {
    case SUCCESS: return "SUCCESS";
    case GENERIC_ERROR: return "GENERIC_ERROR";
    case NULLPTR_PARAMETER_ERROR: return "NULLPTR_PARAMETER_ERROR";
    case OPEN_FILE_FAILED: return "OPEN_FILE_FAILED";
    case READ_FAILED: return "READ_FAILED";
    case MALFORMED_STATUS_LINE: return "MALFORMED_STATUS_LINE";
    case UID_NOT_FOUND: return "UID_NOT_FOUND";
    case USER_NOT_FOUND: return "USER_NOT_FOUND";
    case MEMORY_ALLOCATION_FAILED: return "MEMORY_ALLOCATION_FAILED";
    case PARSING_FAILED: return "PARSING_FAILED";
    case THREAD_FAILED: return "THREAD_FAILED";
    case SEND_SIGNAL_PIDFD_OPEN_FAILED: return "SEND_SIGNAL_PIDFD_OPEN_FAILED";
    case SEND_SIGNAL_SEND_FAILED: return "SEND_SIGNAL_SEND_FAILED";
    case SEND_SIGNAL_WAIT_FAILED: return "SEND_SIGNAL_WAIT_FAILED";
    case PID_DOES_NOT_EXIST: return "PID_DOES_NOT_EXIST";
    case FORK_FAILED: return "FORK_FAILED";
    case TIMEOUT: return "TIMEOUT";
    case READ_CFG_SERVER_NAME_FAILED: return "READ_CFG_SERVER_NAME_FAILED";
    case READ_CFG_SERVER_ADDR_FAILED: return "READ_CFG_SERVER_ADDR_FAILED";
    case READ_CFG_PORT_FAILED: return "READ_CFG_PORT_FAILED";
    case READ_CFG_USERNAME_FAILED: return "READ_CFG_USERNAME_FAILED";
    case READ_CFG_PASSWORD_FAILED: return "READ_CFG_PASSWORD_FAILED";
    case READ_CFG_CONNEXION_FAILED: return "READ_CFG_CONNEXION_FAILED";
    case INVALID_ARGUMENT: return "INVALID_ARGUMENT";
    case UNREGULAR_FILE_ERROR: return "UNREGULAR_FILE_ERROR";
    case BAD_PERMISSIONS_ERROR: return "BAD_PERMISSIONS_ERROR";
    case CPU_NOT_FOUND: return "CPU_NOT_FOUND";
    case BTIME_NOT_FOUND: return "BTIME_NOT_FOUND";
    case DOT_CONFIG_NOT_FOUND: return "DOT_CONFIG_NOT_FOUND";
    case FILE_DOES_NOT_EXIST: return "FILE_DOES_NOT_EXIST";
    case PATH_TOO_LONG_ERROR: return "PATH_TOO_LONG_ERROR";
    case BUFFER_TOO_LONG: return "BUFFER_TOO_LONG";
    case INVALID_PATH: return "INVALID_PATH";
    case BUFFER_OVERFLOW: return "BUFFER_OVERFLOW";
    case SSH_CONNEXION_FAILED: return "SSH_CONNEXION_FAILED";
    case SSH_OPEN_FAILED: return "SSH_OPEN_FAILED";
    case SSH_REQUEST_FAILED: return "SSH_REQUEST_FAILED";
    case SSH_READ_FAILED: return "SSH_READ_FAILED";
    case SSH_GET_FILE_FAILED: return "SSH_GET_FILE_FAILED";
    case SPECIAL_EXIT: return "SPECIAL_EXIT";
    default: return "UNKNOWN_ERROR";
    }
}
