#ifndef ERROR_H
#define ERROR_H

/**
 * @brief Enumérateur utilisé pour renvoyer toutes les erreurs dont on a besoin dans le code
 */
typedef enum error_code_t : int {
  SUCCESS,
  GENERIC_ERROR,
  NULLPTR_PARAMETER_ERROR,
  OPEN_FILE_FAILED,
  READ_FAILED,
  MALFORMED_STATUS_LINE,

  UID_NOT_FOUND,
  USER_NOT_FOUND,
  CPU_NOT_FOUND,
  BTIME_NOT_FOUND,
  DOT_CONFIG_NOT_FOUND,

  MEMORY_ALLOCATION_FAILED,
  THREAD_FAILED,
  SEND_SIGNAL_PIDFD_OPEN_FAILED,
  SEND_SIGNAL_SEND_FAILED,
  SEND_SIGNAL_WAIT_FAILED,
  PID_DOES_NOT_EXIST,
  FORK_FAILED,
  TIMEOUT,
  
  READ_CFG_SERVER_NAME_FAILED,
  READ_CFG_SERVER_ADDR_FAILED,
  READ_CFG_PORT_FAILED,
  READ_CFG_USERNAME_FAILED,
  READ_CFG_PASSWORD_FAILED,
  READ_CFG_CONNEXION_FAILED,
  
  INVALID_ARGUMENT,
  FILE_DOES_NOT_EXIST,
  UNREGULAR_FILE_ERROR,
  BAD_PERMISSIONS_ERROR,
  PATH_TOO_LONG_ERROR,
  BUFFER_TOO_LONG,
  INVALID_PATH,
  BUFFER_OVERFLOW,
  PARSING_FAILED,

  SSH_CONNEXION_FAILED,
  SSH_OPEN_FAILED,
  SSH_REQUEST_FAILED,
  SSH_READ_FAILED,
  SSH_GET_FILE_FAILED,

  SPECIAL_EXIT,
} error_code_t;

/**
 * @brief Change un code d'erreur en chaîne de caractère
 *
 * @param err Erreur à changer
 *
 * @return Chaîne de caractère du code d'erreur
 */
const char *err_to_str(const error_code_t err);

#endif // ERROR_H
